services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restdb
      MYSQL_USER: restadmin
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./src/scripts/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql:ro
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
